{{-- @extends('layouts.app')
@section('content')
    <!-- Main content -->
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-3 bg-light sidebar">
                <h4 class="my-4">Amazon Listing Generator</h4>
                <form id="product-form">
                    <div class="form-group">
                        <label for="product-name">Product Name:</label>
                        <input type="text" id="product-name" name="product_name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="product-description">Product Description:</label>
                        <textarea id="product-description" name="product_description" class="form-control" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="length-limit">Length Limit:</label>
                        <select class="form-control" id="length-limit">
                            <option value="200">200 Bytes</option>
                            <option value="250">250 Bytes</option>
                            <option value="500">500 Bytes</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description-length">Description Length:</label>
                        <select class="form-control" id="description-length">
                            <option value="1">1 Paragraph</option>
                            <option value="3">3 Paragraphs</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary mt-2">Generate Listing</button>
                </form>
            </div>
            <!-- Main content area -->
            <div class="col-md-9 mb-5">
                <h5 class="mt-3 mb-1">This is where your listings will show up.</h5>
                <p>Please note that the quality of the results generated by the AI will improve with more detailed and
                    accurate inputs.</p>
                <div id="loader" style="display: none;">
                    <div class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <p id="product-names"></p>
                <p id="product-descriptions"></p>
            </div>
        </div>
    </div>
@endsection --}}

@extends('layouts.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <!-- Sidebar -->
        <div class="col-md-3">
            <div class="card shadow-sm border-0 rounded-lg">
                <div class="card-body">
                    <h4 class="text-primary mb-4 text-center fw-bold">
                        <i class="bi bi-amazon"></i> Amazon Listing Generator
                    </h4>
                    <form id="product-form">
                        <div class="form-group mb-3">
                            <label for="product-name" class="form-label fw-semibold">Product Name</label>
                            <input type="text" id="product-name" name="product_name" class="form-control" placeholder="Enter product name">
                        </div>

                        <div class="form-group mb-3">
                            <label for="product-description" class="form-label fw-semibold">Product Description</label>
                            <textarea id="product-description" name="product_description" class="form-control" rows="5" placeholder="Describe your product"></textarea>
                        </div>

                        <div class="form-group mb-3">
                            <label for="length-limit" class="form-label fw-semibold">Length Limit</label>
                            <select class="form-control" id="length-limit">
                                <option value="200">200 Bytes</option>
                                <option value="250">250 Bytes</option>
                                <option value="500">500 Bytes</option>
                            </select>
                        </div>

                        <div class="form-group mb-3">
                            <label for="description-length" class="form-label fw-semibold">Description Length</label>
                            <select class="form-control" id="description-length">
                                <option value="1">1 Paragraph</option>
                                <option value="2">2 Paragraph</option>
                                <option value="3">3 Paragraphs</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary w-100 py-2 fw-semibold">
                            <i class="bi bi-lightning-charge"></i> Generate Listing
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <div class="col-md-9">
            <div class="card shadow-sm border-0 rounded-lg mb-4">
                <div class="card-body">
                    <h5 class="fw-bold text-secondary mb-2">Generated Listings</h5>
                    <p class="text-muted small mb-3">
                        The more detailed your inputs, the better the AI results will be.
                    </p>

                    <!-- Loader -->
                    <div id="loader" class="text-center py-4" style="display: none;">
                        {{-- <div class="spinner-border text-primary" role="status" style="width: 3rem; height: 3rem;">
                            <span class="visually-hidden">Loading...</span>
                        </div> --}}
                        <p class="mt-2 text-muted">Generating your listing...</p>
                    </div>

                    <!-- Output -->
                    <div id="product-names" class="fw-bold text-primary mb-2"></div>
                    <div id="product-descriptions" class="text-dark"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Optional: Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
@endsection
