@extends('layouts.app')
@section('content')
    <!-- Main content -->
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-3 bg-light sidebar">
                <h4 class="my-4">Amazon Listing Generator</h4>
                <form id="product-form">
                    <div class="form-group">
                        <label for="product-name">Product Name:</label>
                        <input type="text" id="product-name" name="product_name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="product-description">Product Description:</label>
                        <textarea id="product-description" name="product_description" class="form-control" rows="5"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="length-limit">Length Limit:</label>
                        <select class="form-control" id="length-limit">
                            <option value="200">200 Bytes</option>
                            <option value="250">250 Bytes</option>
                            <option value="500">500 Bytes</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description-length">Description Length:</label>
                        <select class="form-control" id="description-length">
                            <option value="1">1 Paragraph</option>
                            <option value="3">3 Paragraphs</option>
                        </select>
                    </div>

                    {{-- <div class="form-group">
                        <label for="language">Select Language:</label>
                        <select class="form-control" id="language">
                          <option value="en">English</option>
                          <option value="es">Spanish</option>
                          <option value="fr">French</option>
                          <option value="de">German</option>
                          <option value="it">Italian</option>
                          <option value="nl">Dutch</option>
                          <option value="pt">Portuguese</option>
                          <option value="ru">Russian</option>
                          <option value="zh">Chinese</option>
                          <option value="ja">Japanese</option>
                          <option value="ko">Korean</option>
                        </select>
                    </div> --}}
                      
                    <button type="submit" class="btn btn-primary mt-2">Generate Listing</button>
                </form>
            </div>
            <!-- Main content area -->
            <div class="col-md-9 mb-5">
                <h5 class="mt-2 mb-1">This is where your listings will show up.</h5>
                <p>Please note that the quality of the results generated by the AI will improve with more detailed and
                    accurate inputs.</p>
                <div id="loader" style="display: none;">
                    <div class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div id="product-names"></div>
                <div id="product-descriptions"></div>
            </div>
        </div>
    </div>
@endsection
