@extends('layouts.app')

@section('content')
    <!-- Main content -->
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-3 bg-light sidebar">
                <h4 class="my-4">Amazon Listing Generator</h4>
                <form id="product-form">
                    <div class="form-group">
                        <label for="product-name">Product Name:</label>
                        <input type="text" id="product-name" name="product_name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="product-description">Product Description:</label>
                        <textarea id="product-description" name="product_description" class="form-control" rows="5"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Generate Listing</button>
                </form>
            </div>
            <!-- Main content area -->
            <div class="col-md-9">
                <h5 class="mt-2 mb-1">This is where your listings will show up.</h5>
                <p>Please note that the quality of the results generated by the AI will improve with more detailed and
                    accurate inputs.</p>
                <div id="loader" style="display: none;">
                    <div class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div id="listing"></div>
            </div>
        </div>
    </div>
@endsection
